CREATE TABLE STUD08.MY_HALL (
  ID NUMBER(3),
  MANAGER_ID NUMBER(3),
  POS_ID NUMBER(3),
  FLOOR NUMBER(2),
  CONSTRAINT HALL_ID_PK PRIMARY KEY (ID),
  CONSTRAINT SYS_C00167095 FOREIGN KEY (POS_ID)
    REFERENCES STUD08.MY_POINT_OF_SALE(ID))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE OR REPLACE TRIGGER STUD08.SEM_H
  AFTER INSERT OR UPDATE OR DELETE ON STUD08.MY_HALL FOR EACH ROW
DECLARE
 v_ChangeType VARCHAR2(10);
 NAME_COL VARCHAR2(30);
 OLD_VAL VARCHAR2(20);
 NEW_VAL VARCHAR2(20);
 TYPE MYCOLUMNS IS VARRAY(6) OF VARCHAR2(15);
 COLUMNS_P MYCOLUMNS;
 NEW_C MYCOLUMNS;
 OLD_C MYCOLUMNS;
 TOTAL INTEGER;
 N_ID NUMBER(10);
 CH NUMBER;
BEGIN

SELECT SEM_LOG_SEQ.NEXTVAL INTO N_ID FROM DUAL;
    
IF INSERTING THEN
  v_ChangeType := 'INSERT';

  COLUMNS_P := MYCOLUMNS('ID','MANAGER_ID','POS_ID','FLOOR');
  NEW_C := MYCOLUMNS(:NEW.ID, :NEW.MANAGER_ID, :NEW.POS_ID, :NEW.FLOOR);
  TOTAL := COLUMNS_P.COUNT;

  OLD_VAL := NULL;

 FOR I IN 1 .. TOTAL LOOP
  INSERT INTO SEM_LOG
  VALUES (N_ID, I, SYSDATE, v_ChangeType, 'MY_HALL', COLUMNS_P(I), OLD_VAL, NEW_C(I), :NEW.ID);
 END LOOP;

ELSIF UPDATING THEN
 v_ChangeType := 'UPDATE' ;

 IF UPDATING('ID') THEN
  NAME_COL := 'ID';
  OLD_VAL := :OLD.ID;
  NEW_VAL := :NEW.ID;
  CH := :NEW.ID;
 END IF;

 IF UPDATING('MANAGER_ID') THEN
  NAME_COL := 'MANAGER_ID';
  OLD_VAL := :OLD.MANAGER_ID;
  NEW_VAL := :NEW.MANAGER_ID;
  CH := :OLD.ID;
 END IF;

 IF UPDATING('POS_ID') THEN
  NAME_COL := 'POS_ID';
  OLD_VAL := :OLD.POS_ID;
  NEW_VAL := :NEW.POS_ID;
  CH := :OLD.ID;
 END IF;

 IF UPDATING('FLOOR') THEN
  NAME_COL := 'FLOOR';
  OLD_VAL := :OLD.FLOOR;
  NEW_VAL := :NEW.FLOOR;
  CH := :OLD.ID;
 END IF;
    
 INSERT INTO SEM_LOG
 VALUES(N_ID, 1, SYSDATE, v_ChangeType,'MY_HALL', NAME_COL, OLD_VAL, NEW_VAL, CH);
ELSE
 v_ChangeType := 'DELETE' ;

  COLUMNS_P := MYCOLUMNS('ID','MANAGER_ID','POS_ID','FLOOR');
  OLD_C := MYCOLUMNS(:OLD.ID, :OLD.MANAGER_ID, :OLD.POS_ID, :OLD.FLOOR);
  TOTAL := COLUMNS_P.COUNT;

  NEW_VAL := NULL;

 FOR I IN 1 .. TOTAL LOOP
  INSERT INTO SEM_LOG
  VALUES (N_ID, I, SYSDATE, v_ChangeType, 'MY_HALL', COLUMNS_P(I), OLD_C(I), NEW_VAL, :OLD.ID);
 END LOOP;
END IF;
END;
/

