CREATE OR REPLACE PACKAGE STUD08.SEM1 AS
PROCEDURE INSERT_EMPLOYEE(N_ID NUMBER, N_FN VARCHAR2, N_LN VARCHAR2, NEW_HID NUMBER, N_SAL NUMBER);
PROCEDURE INSERT_HALL(N_ID NUMBER, N_MID NUMBER, N_POSID NUMBER, N_FLOOR NUMBER);
PROCEDURE INSERT_POINT_OF_SALE(N_ID NUMBER, N_NAME VARCHAR2, N_TYPE VARCHAR2, N_FLOORS NUMBER, N_SQUARE NUMBER, N_UC NUMBER);

PROCEDURE UPDATE_EMPLOYEE(N_ID NUMBER, N_COLUMN VARCHAR2, N_VALUE VARCHAR2);
PROCEDURE UPDATE_HALL(N_ID NUMBER, N_COLUMN VARCHAR2, N_VALUE VARCHAR2);
PROCEDURE UPDATE_POINT_OF_SALE(N_ID NUMBER, N_COLUMN VARCHAR2, N_VALUE VARCHAR2);

PROCEDURE DELETE_EMPLOYEE(N_ID NUMBER);
PROCEDURE DELETE_HALL(N_ID NUMBER);
PROCEDURE DELETE_POINT_OF_SALE(N_ID NUMBER);
END SEM1;
/

CREATE OR REPLACE PACKAGE BODY STUD08.SEM1 AS

PROCEDURE INSERT_EMPLOYEE(N_ID NUMBER, N_FN VARCHAR2, N_LN VARCHAR2, NEW_HID NUMBER, N_SAL NUMBER)
AS
CH NUMBER;
BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_EMPLOYEE
WHERE ID = N_ID;

IF CH <> 0 THEN
DBMS_OUTPUT.PUT_LINE('Element exists');
RETURN;
END IF;

INSERT INTO MY_EMPLOYEE
VALUES (N_ID, N_FN, N_LN, NEW_HID, N_SAL);
END;

-----------------------------------------------------

PROCEDURE INSERT_HALL(N_ID NUMBER, N_MID NUMBER, N_POSID NUMBER, N_FLOOR NUMBER)
AS
CH NUMBER;
BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_HALL
WHERE ID = N_ID;

IF CH <> 0 THEN
DBMS_OUTPUT.PUT_LINE('Element exists');
RETURN;
END IF;

CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_HALL
WHERE ID = N_POSID;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('Point of sale does not exists');
RETURN;
END IF;

INSERT INTO MY_HALL
VALUES (N_ID, N_MID, N_POSID, N_FLOOR);
END;

-----------------------------------------------------

PROCEDURE INSERT_POINT_OF_SALE(N_ID NUMBER, N_NAME VARCHAR2, N_TYPE VARCHAR2, N_FLOORS NUMBER, N_SQUARE NUMBER, N_UC NUMBER)
AS
CH NUMBER;
BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_POINT_OF_SALE
WHERE ID = N_ID OR LOWER(NAME) = LOWER(N_NAME);

IF CH <> 0 THEN
DBMS_OUTPUT.PUT_LINE('Element exists');
RETURN;
END IF;

INSERT INTO MY_POINT_OF_SALE
VALUES (N_ID, N_NAME, N_TYPE, N_FLOORS, N_SQUARE, N_UC);
END;

-----------------------------------------------------

PROCEDURE UPDATE_EMPLOYEE(N_ID NUMBER, N_COLUMN VARCHAR2, N_VALUE VARCHAR2)
AS
CH NUMBER;
RECORDING VARCHAR2(100);
BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM all_tab_columns
WHERE TABLE_NAME = 'MY_EMPLOYEE' AND COLUMN_NAME = N_COLUMN;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The columns does not exist');
RETURN;
END IF;

CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_EMPLOYEE
WHERE ID = N_ID;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The employee does not exist');
RETURN;
END IF;

RECORDING := 
'UPDATE MY_EMPLOYEE
SET ' || N_COLUMN || ' = '''|| N_VALUE ||'''
WHERE ID = ' || N_ID;

DBMS_OUTPUT.PUT_LINE(RECORDING);

EXECUTE IMMEDIATE RECORDING;
END;

-----------------------------------------------------

PROCEDURE UPDATE_HALL(N_ID NUMBER, N_COLUMN VARCHAR2, N_VALUE VARCHAR2)
AS
CH NUMBER;
RECORDING VARCHAR2(100);
BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM all_tab_columns
WHERE TABLE_NAME = 'MY_HALL' AND COLUMN_NAME = N_COLUMN;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The columns does not exist');
RETURN;
END IF;

CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_EMPLOYEE
WHERE ID = N_ID;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The hall does not exist');
RETURN;
END IF;

RECORDING := 
'UPDATE MY_HALL
SET ' || N_COLUMN || ' = '''|| N_VALUE ||'''
WHERE ID = ' || N_ID;

DBMS_OUTPUT.PUT_LINE(RECORDING);

EXECUTE IMMEDIATE RECORDING;
END;

-----------------------------------------------------

PROCEDURE UPDATE_POINT_OF_SALE(N_ID NUMBER, N_COLUMN VARCHAR2, N_VALUE VARCHAR2)
AS
CH NUMBER;
RECORDING VARCHAR2(100);
BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM all_tab_columns
WHERE TABLE_NAME = 'MY_POINT_OF_SALE' AND COLUMN_NAME = N_COLUMN;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The columns does not exist');
RETURN;
END IF;

CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_EMPLOYEE
WHERE ID = N_ID;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The point of sale does not exist');
RETURN;
END IF;

RECORDING := 
'UPDATE MY_POINT_OF_SALE
SET ' || N_COLUMN || ' = '''|| N_VALUE ||'''
WHERE ID = ' || N_ID;

DBMS_OUTPUT.PUT_LINE(RECORDING);

EXECUTE IMMEDIATE RECORDING;
END;

-----------------------------------------------------

PROCEDURE DELETE_EMPLOYEE(N_ID NUMBER)
AS
CH NUMBER;

BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_EMPLOYEE
WHERE ID = N_ID;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The employee does not exist');
RETURN;
END IF;

DELETE FROM MY_EMPLOYEE
WHERE ID = N_ID;
END;

-----------------------------------------------------

PROCEDURE DELETE_HALL(N_ID NUMBER)
AS
CH NUMBER;

BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_HALL
WHERE ID = N_ID;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The hall does not exist');
RETURN;
END IF;

DELETE FROM MY_HALL
WHERE ID = N_ID;
END;

-----------------------------------------------------

PROCEDURE DELETE_POINT_OF_SALE(N_ID NUMBER)
AS
CH NUMBER;

BEGIN
CH := 0;

SELECT COUNT(*)
INTO CH
FROM MY_POINT_OF_SALE
WHERE ID = N_ID;

IF CH = 0 THEN
DBMS_OUTPUT.PUT_LINE('The point of sale does not exist');
RETURN;
END IF;

DELETE FROM MY_POINT_OF_SALE
WHERE ID = N_ID;
END;
END SEM1;
/

